"""
Django settings for kiuf_elib project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here-change-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['itopik.uz', 'www.itopik.uz', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'apscheduler',
    'django_apscheduler',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kiuf_elib.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiuf_elib.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL Database Configuration
# Quyidagi qadamlar bilan PostgreSQL-ni sozlash mumkin:
# 1. Tizimingizda PostgreSQL serverini o'rnating.
#    - Windows uchun: https://www.postgresql.org/download/windows/ saytidan yuklab oling
#    - Linux/Mac uchun: paket menejeridan foydalaning (apt install postgresql, brew install postgresql)
# 2. PostgreSQL xizmatini ishga tushiring.
# 3. Ma'lumotlar bazasi foydalanuvchisini va bazasini yarating:
#    - psql yoki pgAdmin-ni oching
#    - CREATE DATABASE your_db_name;
#    - CREATE USER your_username WITH PASSWORD 'your_password';
#    - GRANT ALL PRIVILEGES ON DATABASE your_db_name TO your_username;
# 4. Python PostgreSQL adapterini o'rnating:
#    - pip install psycopg2-binary
#    - requirements.txt fayliga 'psycopg2-binary' qo'shing
# 5. Quyidagi DATABASES sozlamasini haqiqiy ma'lumotlar bazasi tafsilotlari bilan yangilang.
# 6. Migratsiyalarni ishga tushiring: python manage.py migrate
# 7. Agar SQLite-dan migratsiya qilsangiz, ma'lumotlarni dump qilib, tiklash kerak bo'lishi mumkin.
# Agar PostgreSQL mavjud bo'lmasa yoki ulana olmasa, avtomatik ravishda SQLite ishlatiladi.
# Qo'shimcha hujjatlar: https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL-ni sinab ko'rish, agar ulana olmasa yoki o'rnatilmagan bo'lsa, SQLite fallback
try:
    import psycopg2
    # Ulashishni sinab ko'rish
    conn = psycopg2.connect(
        dbname='your_db_name',  # O'zingizning ma'lumotlar bazasi nomini kiriting
        user='your_username',  # Ma'lumotlar bazasi foydalanuvchisini kiriting
        password='your_password',  # Parolni kiriting
        host='localhost',  # Ma'lumotlar bazasi hosti, odatda localhost
        port='5432'  # PostgreSQL-ning standart porti
    )
    conn.close()
    # Agar ulanish muvaffaqiyatli bo'lsa, PostgreSQL ishlatiladi
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'your_db_name',  # O'zingizning ma'lumotlar bazasi nomini kiriting
            'USER': 'your_username',  # Ma'lumotlar bazasi foydalanuvchisini kiriting
            'PASSWORD': 'your_password',  # Parolni kiriting
            'HOST': 'localhost',  # Ma'lumotlar bazasi hosti, odatda localhost
            'PORT': '5432',  # PostgreSQL-ning standart porti
        }
    }
except (ImportError, psycopg2.OperationalError):
    # psycopg2 o'rnatilmagan yoki ulana olmasa, SQLite ishlatiladi
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'accounts.authentication.HemisIDBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'https://itopik.uz',
    'https://www.itopik.uz',
    'http://itopik.uz',
    'http://www.itopik.uz',
    'http://localhost',
    'http://127.0.0.1',
    'https://localhost',
    'https://127.0.0.1',
]

# Disable CSRF cookie security for development (allow HTTP)
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom authentication
AUTH_USER_MODEL = 'accounts.Student'
AUTHENTICATION_BACKENDS = [
    'accounts.backends.HemisAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'library:home'
LOGOUT_REDIRECT_URL = 'library:home'

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = True

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Kutubxona Admini",
    "SITE_HEADER": "Kutubxona Admini",
    "SITE_URL": "/",
    "SITE_ICON": lambda request: "/static/css/logo.png",
    "THEME": "dark",
    "LOGIN": {
        "image": lambda request: "/static/css/logo.png",
        "redirect_after": lambda request: "/admin/",
    },
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [],
    },
}
